### ISSUE TITLE
InstructionFabric implementation

### ISSUE THREAD

**Issue by Cianidos** [Cianidos/CellsLifeSimulation#2]
Task:
Implement InstructionFabric

**Comment by Cianidos** [comment]
Instruction fabric provides ready to use instructions with parameters for LifeCycle.
`
....
var lifeCycle = new LifeCycle();
var inst = InstruciontFabric.MakeMoney(100);
var instFor = InstructionFabric.CycleNextInstrucion();
lifeCycle.AddInstruciton(instFor);
lifeCycle.AddInstrucition(inst);
....
 `

**Comment by Shennor** [comment]
Done

**Comment by Shennor** [comment]
Done ^_^
